In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
columns_to_drop = ['EIN', 'NAME']
application_df.drop(columns_to_drop, axis=1, inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()
print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
threshold = 2
application_types_to_replace = application_type_counts[application_type_counts < threshold].index
application_df['APPLICATION_TYPE'].replace(application_types_to_replace, 'Other', inplace=True)
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
T25          3
T14          3
T29          2
T15          2
Other        1
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
threshold = 2
classifications_to_replace = classification_counts[classification_counts < threshold].index
application_df['CLASSIFICATION'].replace(classifications_to_replace, 'Other', inplace=True)

In [ ]:
threshold = 2
classifications_to_replace = classification_counts[classification_counts < threshold].index
application_df['CLASSIFICATION'].replace(classifications_to_replace, 'Other', inplace=True)

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Other       26
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C1267        2
C1256        2
C1234        2
C1246        2
C3200        2
Name: count, dtype: int64

In [ ]:
y = application_df['IS_SUCCESSFUL']
X = application_df.drop(columns = 'IS_SUCCESSFUL')
X = pd.get_dummies(X)
X

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

Shape of X: (34299, 91)
Shape of y: (34299,)

In [ ]:
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
num_columns = X.shape[1]
print("Number of columns in X:", num_columns)

Number of columns in X: 91

In [ ]:
import tensorflow as tf
from tensorflow import keras

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(keras.layers.Dense(50, activation='relu'))

# Second hidden layer
nn.add(keras.layers.Dense(50, activation='relu'))

# Output layer
nn.add(keras.layers.Dense(1, activation='sigmoid'))

nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

nn.fit(X_train_scaled, y_train, epochs=10)


# Check the structure of the model
nn.summary()

Epoch 1/10
804/804 [==============================] - 4s 3ms/step - loss: 0.5729 - accuracy: 0.7214
Epoch 2/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7304
Epoch 3/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7310
Epoch 4/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7315
Epoch 5/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7331
Epoch 6/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7344
Epoch 7/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 8/10
804/804 [==============================] - 3s 4ms/step - loss: 0.5438 - accuracy: 0.7333
Epoch 9/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7342
Epoch 10/10
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7353
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                4600

 dense_1 (Dense)             (None, 50)                2550

 dense_2 (Dense)             (None, 1)                 51

=================================================================
Total params: 7201 (28.13 KB)
Trainable params: 7201 (28.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5428 - accuracy: 0.7357
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7365
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7359
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7364
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7367
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7384
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7372
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7375
Epoch 10/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7387
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7381
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7389
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7389
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7377
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7390
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7379
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7371
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7405
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7396
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7398
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7382
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7393
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7398
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7406
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7407
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7395
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7399
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7390
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7400
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7407
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7396
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7402
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7400
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7413
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7407
Epoch 40/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5318 - accuracy: 0.7409
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7407
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7411
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7405
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7403
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7413
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7421
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7402
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7416

In [ ]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5580 - accuracy: 0.7303 - 917ms/epoch - 3ms/step
Loss: 0.5579624176025391, Accuracy: 0.7302623987197876

In [ ]:
nn.save("AlphabetSoupCharity3.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(